# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Buckingham AP Computer Science Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: Discuss concepts, homework, assignments and more!

# Your name, as you want it to appear underneath each post and in the footer
author: Cristina Muñoz

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
# baseurl: /Jekyll-Disqus-Forum

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://xmunoz.github.io/APCS-forum

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: apcomputerscience

# The public key for your disqus application
disqus_publickey: mSdYK0JfxqGAuqp7HXbbItRP6scjl4TqRh1ZY1a7PJlHWCN7jPOupRhOqhMdwaeh 
